title: <p align="center">Mallikarjun Reddy<P>
logo: /assets/img/logo.png
 <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  I'm working on Data Engineering, Snowflake, Python, Machine learning & NLP related problems.
  Working in Finance domain for 3 years.
  <br>
  </p>
theme: jekyll-theme-minimal
